### ISSUE TITLE
ODBC DSN Test Connection crash on earlier versions of Windows

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-sql-odbc#147] opened 2019-04-26 21:34 UTC
Just filing to share a crash event for those who may run into something similar on unsupported Windows OSes.

![image](https://user-images.githubusercontent.com/7216393/56837655-0bf78300-6830-11e9-93b5-e9dd1f45f40a.png)
![image](https://user-images.githubusercontent.com/7216393/56837799-87593480-6830-11e9-98cf-ef51d6fa036b.png)

[crash_event.xml.zip](https://github.com/elastic/elasticsearch-sql-odbc/files/3123057/crash_event.xml.zip)

Certainly, Windows 2012 R2 does not meet the pre-requisites for the ODBC driver installation.  However, we currently allow the ODBC driver to install successfully (without errors) on this OS version (https://github.com/elastic/elasticsearch-sql-odbc/issues/146).  

I am actually able to bring data into Excel on this OS version and it appears to work fine; the piece that crashes is the Test Connection button from the DSN setup.

**Comment by bpintea** [comment] 2019-05-02 09:30
Thanks, @ppf2.
I believe this had been fixed in #134 already and it shouldn't occur in any post 6.7.0 releases anymore.

**Comment by bpintea** [comment] 2019-05-03 19:02
duplicate of #133

**Closed by bpintea** 2019-05-03 19:02 UTC
Labels: duplicate
